if(typeof MTVN=="undefined"){MTVN={};
}if(typeof MTVN.config=="undefined"){MTVN.config={};
}if(typeof MTVN.config.btg=="undefined"){MTVN.config.btg={};
}if(typeof MTVN.config.btg.DoubleClick=="undefined"){MTVN.config.btg.DoubleClick={};
}MTVN.config.btg.DoubleClick.auto=false;
var vmn_page_data={metadata:{property:"nickjr"},mappings:{"ad-unit":{"1":"@property"},"key-values":{}}};
function setVMNPageData(){try{var j,k,i,d;
var c=location.hostname;
var f="";
var a=location.pathname.replace(/-/g,"_").split("/");
if(a[a.length-1]==""&&a[1]!=""){a.pop();
}if(KIDS.IS_DEV==true){console.log(">>>>>>>>>KFAR ADS: url info ");
console.log(a);
}if(c.indexOf("beyondthebackpack")!=-1){j="beyond_the_backpack";
k="home";
}else{if(a[1]=="kids_health"){j="parenting";
k="family";
f="family_life,family_life_group";
}else{if(a[1]=="recipes"){j="parenting";
k="family";
f="recipes,home";
}else{if(a[1].indexOf("_party")!=-1){j="parenting";
k="family";
f="birthdays_group,birthdays";
}else{if(KIDS.get("categoryPath")&&a[1]!="shows"){var h=KIDS.get("categoryPath");
if(h.indexOf("/family/")!=-1){vCat=h.substr(h.lastIndexOf("/")+1);
j="parenting";
k="family";
f=vCat+",home";
}else{if(h.indexOf("/nickjr-monthly-themes/")!=-1){j="parenting";
k="family";
d=h.replace(/-/g,"_");
if(d.indexOf("_printables")!=-1){f=d+",crafts";
}else{if(d.indexOf("_videos")!=-1){f=d+",videos";
}else{f=d+",home";
}}}else{if(h.indexOf("/2009-Redesign/shows/")!=-1){j="parenting";
k="shows_parenting";
if(KIDS.get("showId")!=""){var b=KIDS.get("showId");
if(b.indexOf("_")!=-1){b=KIDS.get("showId");
}i=b;
}}else{if(h.indexOf("/2009-Redesign/kids")!=-1){j="playtime";
k="shows_playtime";
if(h.indexOf("/games")!=-1){if(a.length==2){k="games";
f="home";
}else{if(KIDS.get("showId")){i=KIDS.get("showId");
}f="games";
}}else{if(h.indexOf("/shows")!=-1){if(KIDS.get("showId")){i=KIDS.get("showId");
}f="home";
}else{if(h.indexOf("/videos")!=-1){k="videos";
if(a.length==2){f="home";
}else{f="featured";
}}else{if(h.indexOf("/nickjr20122015/creativity-center")!=-1){k="create";
if(KIDS.get("urlAlias")=="nick-jr-coloring-book"){f="coloring_game";
}else{f="home";
}}else{if(KIDS.get("urlAlias")=="kids-homepage"){k="home";
}}}}}}else{if(h.indexOf("/family")!=-1){j="parenting";
k=(a[1].length>0)?a[1]:"home";
}else{if(h.indexOf("nick-jr-newsletters/sign-up")!=-1){j="parenting";
k="newsletters";
i="home";
f="home";
}}}}}}}else{if(a[1]=="printables"||a[1]=="crafts"||a[1]=="recipes"){j="parenting";
k="shows_parenting";
if(a[2]=="dora_the_explorer"){i="dora";
}else{i=a[2];
}}else{if(a.length==2){j="parenting";
k=(a[1].length>0)?a[1]:"home";
if(a[1]=="shows"){j="parenting";
k="shows_parenting";
f="home";
}else{if(a[1]=="parties"){j="parenting";
k="family";
f="birthdays,home";
}else{if(a[1]=="games_activities"){j="parenting";
k="family";
f="games_activities,home";
}else{if(a[1]=="spring_activities"){j="parenting";
k="family";
f="spring,home";
}else{if(a[1]=="family_life"){j="parenting";
k="family";
f="family_life,home";
}else{if(a[1]=="printables"){j="parenting";
k="family";
f="games_activities,parties";
}else{if(a[1]=="video"){j="parenting";
k="family";
if(location.search.indexOf("videoid=")!=-1){f="videos";
}else{f="videos,home";
}}}}}}}}}else{if(a.length==3){if(a[1]=="video"){j="parenting";
k="family";
if(location.search.indexOf("videoid=")!=-1){f="videos";
}else{f="videos,home";
}}else{if(a[2]=="tv_schedule.html"){j="parenting";
k="tv_schedule";
i="home";
f="home";
}else{if(a[1]=="kids_videos"){j="playtime";
if(a[2].split("_")[0]=="featured"){k="videos";
f="featured";
}else{k="shows_playtime";
if(KIDS.get("showId")){i=KIDS.get("showId");
}f="videos";
}}}}}else{if(a.length>3){if(a[2]=="my_dora_video"){j="parenting";
k="shows_parenting";
i="dora";
}}}}}}}}}}if(j){vmn_page_data.metadata.hub=j;
vmn_page_data.mappings["ad-unit"]["2"]="@hub";
}if(k){vmn_page_data.metadata.hubNode=k;
vmn_page_data.mappings["ad-unit"]["3"]="@hubNode";
}if(i){vmn_page_data.metadata.endLevel=i;
vmn_page_data.mappings["ad-unit"]["4"]="@endLevel";
}f=f.replace(/[- ]/g,"_").toLowerCase();
if(f.length>0){vmn_page_data.mappings["key-values"]["section"]=f;
}if(KIDS.IS_DEV==true){console.log(">>>>>>>>>KFAR ADS: adunit page data ");
console.log(vmn_page_data);
}}catch(g){console.log(">>>>>>>>>KFAR ADS - adunit.js: "+g);
}}setVMNPageData();

if(typeof KIDS=="undefined"||!KIDS){var KIDS={};
}KIDS.namespace("ads.pageLevelAdConfig");
KIDS.ads.pageLevelAdConfig.minSponsor=1;
KIDS.ads.pageLevelAdConfig.maxSponsor=3;
KIDS.ads.pageLevelAdConfig.randSponsor=Math.floor(Math.random()*(KIDS.ads.pageLevelAdConfig.maxSponsor-KIDS.ads.pageLevelAdConfig.minSponsor+1)+KIDS.ads.pageLevelAdConfig.minSponsor);
KIDS.ads.pageLevelAdConfig.zone;
KIDS.ads.pageLevelAdConfig.keyValues;
KIDS.ads.pageLevelAdConfig.init=function(){try{var b=location.pathname;
var g="";
if(b.indexOf(".jhtml")<0){if(b.indexOf(".html")<0){if(b.charAt(b.length-1)!="/"){b+="/";
}b+="index.html";
}if(b.indexOf("ad-entry")>-1){var d=b.split(".");
if(d.length==2){b=d[0]+"/interstitial."+d[1];
}}b=b.replace(/[- ]/gi,"_");
}var a=b.split("/");
if(b.indexOf(".jhtml")<0){if(a.length==2){if(a[1]=="index.html"){b="/_hp";
}}else{if(a.length==3){if(a[2]=="index.html"){b="/"+a[1]+"/_mn";
}}}}if(KIDS.ads.pageLevelAdConfig.maxSponsor>1){g+="cat="+KIDS.ads.pageLevelAdConfig.randSponsor+";";
}if(KIDS.get("urlAlias")){g+="activity="+KIDS.get("urlAlias")+";";
}if(KIDS.get("showId")){g+="!category="+KIDS.get("showId")+";franchise="+KIDS.get("showId")+";";
}if(location.pathname.indexOf("/kids/")>-1||location.pathname.indexOf("/nickjr20122015/kids-games/")>-1||location.pathname.indexOf("/nickjr20122015/kids-videos/")>-1||location.pathname.indexOf("/nickjr20122015/kids-create/")>-1){g+="demo=D;";
}var h=location.search;
if(h.length>0){h=h.replace("?","");
tmp=h.split("&");
for(var c=0;
c<tmp.length;
c++){if(tmp[c].indexOf("testmode")>-1){g+=tmp[c]+";";
}}}if(b.indexOf(".html")>-1){b=b.substring(0,b.indexOf(".html"));
}b=b.replace(/[- ]/gi,"_");
g=g.replace(/[- ]/gi,"_");
KIDS.ads.pageLevelAdConfig.zone=b;
KIDS.ads.pageLevelAdConfig.keyValues=g;
if(KIDS.get("adfree")=="true"){KIDS.ads.pageLevelAdConfig.keyValues+="!category=poe;";
}KIDS.utils.doLog("KIDS.ads.pageLevelAdConfig.zone:"+KIDS.ads.pageLevelAdConfig.zone);
KIDS.utils.doLog("KIDS.ads.pageLevelAdConfig.keyValues:"+KIDS.ads.pageLevelAdConfig.keyValues);
if(typeof MTVN=="undefined"){MTVN={};
}if(typeof MTVN.config=="undefined"){MTVN.config={};
}if(typeof MTVN.config.btg=="undefined"){MTVN.config.btg={};
}if(typeof MTVN.config.btg.DoubleClick=="undefined"){MTVN.config.btg.DoubleClick={};
}MTVN.config.btg.DoubleClick.sections=KIDS.ads.pageLevelAdConfig.zone;
if(location.pathname.indexOf("/nickjr20122015/kids/")==0||location.pathname.indexOf("/kids-games/")==0||location.pathname.indexOf("/nickjr20122015/kids-videos/")==0||location.pathname.indexOf("/nickjr20122015/kids-create/")==0){MTVN.config.btg.DoubleClick.dartSite="nickjr.playtime.nol";
}if(typeof MTVN.config.btg.DoubleClick.keyValues=="string"){MTVN.config.btg.DoubleClick.keyValues+=KIDS.ads.pageLevelAdConfig.keyValues;
}else{MTVN.config.btg.DoubleClick.keyValues=KIDS.ads.pageLevelAdConfig.keyValues;
}}catch(f){KIDS.utils.doLog("pageLevelAdSettings failed:"+f);
}};
KIDS.ads.pageLevelAdConfig.init();