if(typeof KIDS=="undefined"||!KIDS){var KIDS={};
}KIDS.namespace("ads");
KIDS.ads.adArray;
KIDS.ads.Ad=function(a){try{this.ad=a;
this.getSize=function(){return this.ad.size;
};
this.getContentType=function(){if(this.ad.contentType){return this.ad.contentType;
}else{return"adj";
}};
this.getActualSize=function(){if(this.ad.actualSize){return this.ad.actualSize;
}else{return"";
}};
this.getElementID=function(){return this.ad.elementID;
};
this.getKeyValues=function(){return this.ad.keyValues;
};
this.isRefreshable=function(){return(this.ad.refreshable=="true")?true:false;
};
this.getRefreshRate=function(){if(isNaN(this.ad.refreshRate)){return 500;
}return new Number(this.ad.refreshRate);
};
}catch(b){}};
KIDS.ads.getAds=function(b){if(KIDS.ads.adArray!=null){return KIDS.ads.adArray;
}KIDS.ads.adArray=new Array();
for(var a in KIDS.ads.config.ads){KIDS.ads.adArray.push(new KIDS.ads.Ad(KIDS.ads.config.ads[a]));
}return KIDS.ads.adArray;
};
KIDS.ads.getVideoAdFrequency=function(){try{if(KIDS.ads.config.videoAdFrequency){return new Number(KIDS.ads.config.videoAdFrequency);
}else{return 0;
}}catch(a){return 0;
}};

function Configuration(orig){this.orig=orig;
this.setting={};
this.setting.name="";
this.setting.dynamicAccountSelection="false";
this.setting.dynamicAccountList="";
this.setting.linkInternalFilters="";
this.setting.trackExternalLinks=false;
this.setting.trackDownloadLinks=false;
this.setting.trackInlineStats=false;
this.setting.pageName="";
this.setting.hier2="";
this.setting.channel="";
this.setting.prop1="";
this.setting.prop2="";
this.setting.prop3="";
this.setting.prop4="";
this.setting.prop5="";
this.setting.prop6="";
this.setting.prop7="";
this.setting.prop8="";
this.setting.prop9="";
this.setting.prop10="";
this.setting.prop11="";
this.setting.prop12="";
this.setting.prop13="";
this.setting.prop14="";
this.setting.prop15="";
this.setting.prop16="";
this.setting.prop17="";
this.setting.prop18="";
this.setting.prop19="";
this.setting.prop20="";
this.setting.prop23="";
this.setting.prop24="";
this.setting.prop25="";
this.setting.prop26="";
this.setting.prop27="";
this.setting.prop28="";
this.setting.prop29="";
this.setting.prop30="";
this.setting.prop31="";
this.setting.prop32="";
this.setting.prop33="";
this.setting.prop34="";
this.setting.prop35="";
this.setting.prop36="";
this.setting.prop37="";
this.setting.prop38="";
this.setting.prop39="";
this.setting.prop40="";
this.setting.prop41="";
this.setting.prop42="";
this.setting.prop43="";
this.setting.prop44="";
this.setting.prop45="";
this.setting.prop46="";
this.setting.prop47="";
this.setting.prop48="";
this.setting.prop49="";
this.setting.prop50="";
this.setting.eVar1="";
this.setting.eVar2="";
this.setting.eVar3="";
this.setting.eVar4="";
this.setting.eVar5="";
this.setting.eVar6="";
this.setting.eVar7="";
this.setting.eVar8="";
this.setting.eVar9="";
this.setting.eVar10="";
this.setting.eVar11="";
this.setting.eVar12="";
this.setting.eVar13="";
this.setting.eVar14="";
this.setting.eVar15="";
this.setting.eVar16="";
this.setting.eVar17="";
this.setting.eVar18="";
this.setting.eVar19="";
this.setting.eVar20="";
this.setting.eVar21="";
this.setting.eVar22="";
this.setting.eVar23="";
this.setting.eVar24="";
this.setting.eVar25="";
this.setting.eVar26="";
this.setting.eVar27="";
this.setting.eVar28="";
this.setting.eVar29="";
this.setting.eVar30="";
this.setting.eVar31="";
this.setting.eVar32="";
this.setting.eVar33="";
this.setting.eVar34="";
this.setting.eVar35="";
this.setting.eVar36="";
this.setting.eVar37="";
this.setting.eVar38="";
this.setting.eVar39="";
this.setting.eVar40="";
this.setting.eVar41="";
this.setting.eVar42="";
this.setting.eVar43="";
this.setting.eVar44="";
this.setting.eVar45="";
this.setting.eVar46="";
this.setting.eVar47="";
this.setting.eVar48="";
this.setting.eVar49="";
this.setting.eVar50="";
this.setting.list1="";
this.setting.list2="";
this.setting.list3="";
this.setting.campaign="";
this.setting.events="";
this.setting.products="";
this.setting.lnk=false;
this.setting.linkType="";
this.setting.linkName="";
this.showPage=false;
this.videoSuite="";
this.init=function(){if(typeof this.orig!="undefined"){this.setting.name=this.orig.getName();
this.setting.dynamicAccountSelection=this.orig.getDynamicAccountSelection();
this.setting.dynamicAccountList=this.orig.getDynamicAccountList();
this.setting.linkInternalFilters=this.orig.getLinkInternalFilters();
this.setting.trackExternalLinks=this.orig.isTrackExternalLinks();
this.setting.trackDownloadLinks=this.orig.isTrackDownloadLinks();
this.setting.trackInlineStats=this.orig.isTrackInlineStats();
this.setting.pageName=this.orig.getPageName();
this.setting.hier1=this.orig.getHier1();
this.setting.hier2=this.orig.getHier2();
this.setting.channel=this.orig.getChannel();
this.setting.prop1=this.orig.getProp(1);
this.setting.prop2=this.orig.getProp(2);
this.setting.prop3=this.orig.getProp(3);
this.setting.prop4=this.orig.getProp(4);
this.setting.prop5=this.orig.getProp(5);
this.setting.prop6=this.orig.getProp(6);
this.setting.prop7=this.orig.getProp(7);
this.setting.prop8=this.orig.getProp(8);
this.setting.prop9=this.orig.getProp(9);
this.setting.prop10=this.orig.getProp(10);
this.setting.prop11=this.orig.getProp(11);
this.setting.prop12=this.orig.getProp(12);
this.setting.prop13=this.orig.getProp(13);
this.setting.prop14=this.orig.getProp(14);
this.setting.prop15=this.orig.getProp(15);
this.setting.prop16=this.orig.getProp(16);
this.setting.prop17=this.orig.getProp(17);
this.setting.prop18=this.orig.getProp(18);
this.setting.prop19=this.orig.getProp(19);
this.setting.prop20=this.orig.getProp(20);
this.setting.prop23=this.orig.getProp(23);
this.setting.prop24=this.orig.getProp(24);
this.setting.prop25=this.orig.getProp(25);
this.setting.prop26=this.orig.getProp(26);
this.setting.prop27=this.orig.getProp(27);
this.setting.prop28=this.orig.getProp(28);
this.setting.prop29=this.orig.getProp(29);
this.setting.prop30=this.orig.getProp(30);
this.setting.prop31=this.orig.getProp(31);
this.setting.prop32=this.orig.getProp(32);
this.setting.prop33=this.orig.getProp(33);
this.setting.prop34=this.orig.getProp(34);
this.setting.prop35=this.orig.getProp(35);
this.setting.prop36=this.orig.getProp(36);
this.setting.prop37=this.orig.getProp(37);
this.setting.prop38=this.orig.getProp(38);
this.setting.prop39=this.orig.getProp(39);
this.setting.prop40=this.orig.getProp(40);
this.setting.prop41=this.orig.getProp(41);
this.setting.prop42=this.orig.getProp(42);
this.setting.prop43=this.orig.getProp(43);
this.setting.prop44=this.orig.getProp(44);
this.setting.prop45=this.orig.getProp(45);
this.setting.prop46=this.orig.getProp(46);
this.setting.prop47=this.orig.getProp(47);
this.setting.prop48=this.orig.getProp(48);
this.setting.prop49=this.orig.getProp(49);
this.setting.prop50=this.orig.getProp(50);
this.setting.eVar1=this.orig.getEVar(1);
this.setting.eVar2=this.orig.getEVar(2);
this.setting.eVar3=this.orig.getEVar(3);
this.setting.eVar4=this.orig.getEVar(4);
this.setting.eVar5=this.orig.getEVar(5);
this.setting.eVar6=this.orig.getEVar(6);
this.setting.eVar7=this.orig.getEVar(7);
this.setting.eVar8=this.orig.getEVar(8);
this.setting.eVar9=this.orig.getEVar(9);
this.setting.eVar10=this.orig.getEVar(10);
this.setting.list1=this.orig.getList(1);
this.setting.list2=this.orig.getList(2);
this.setting.list3=this.orig.getList(3);
this.setting.campaign=this.orig.getCampaign();
this.setting.events=this.orig.getEvents();
this.setting.products=this.orig.getProducts();
this.showPage=this.orig.isShowPage();
this.videoSuite=this.orig.getVideoSuite();
}};
this.getName=function(){return this.setting.name;
};
this.setName=function(name){this.setting.name=name;
};
this.getDynamicAccountSelection=function(){return this.setting.dynamicAccountSelection;
};
this.setDynamicAccountSelection=function(das){this.setting.dynamicAccountSelection=das;
};
this.getDynamicAccountList=function(){return this.setting.dynamicAccountList;
};
this.setDynamicAccountList=function(dal){this.setting.dynamicAccountList=dal;
};
this.getLinkInternalFilters=function(){return this.setting.linkInternalFilters;
};
this.setLinkInternalFilters=function(lif){this.setting.linkInternalFilters=lif;
};
this.isTrackExternalLinks=function(){return this.setting.trackExternalLinks;
};
this.setTrackExternalLinks=function(tel){this.setting.trackExternalLinks=tel;
};
this.isTrackDownloadLinks=function(){return this.setting.trackDownloadLinks;
};
this.setTrackDownloadLinks=function(tdl){this.setting.trackDownloadLinks=tdl;
};
this.isTrackInlineStats=function(){return this.setting.trackInlineStats;
};
this.setTrackInlineStats=function(tns){this.setting.trackInlineStats=tns;
};
this.getPageName=function(){return this.setting.pageName;
};
this.setPageName=function(pagename){this.setting.pageName=pagename;
};
this.getHier1=function(){return this.setting.hier1;
};
this.setHier1=function(hier1){this.setting.hier1=hier1;
};
this.getHier2=function(){return this.setting.hier2;
};
this.setHier2=function(hier2){this.setting.hier2=hier2;
};
this.getChannel=function(){return this.setting.channel;
};
this.setChannel=function(chan){this.setting.channel=chan;
};
this.isShowPage=function(){return this.showPage;
};
this.setShowPage=function(isSP){this.showPage=isSP;
};
this.getVideoSuite=function(){return this.videoSuite;
};
this.setVideoSuite=function(vs){this.videoSuite=vs;
};
this.getProp=function(n){return(eval("this.setting.prop"+n));
};
this.setProp=function(n,value){eval("this.setting.prop"+n+'="'+value+'"');
};
this.getEVar=function(n){return(eval("this.setting.eVar"+n));
};
this.setEVar=function(n,value){eval("this.setting.eVar"+n+'="'+value+'"');
};
this.getList=function(n){return(eval("this.setting.list"+n));
};
this.setList=function(n,value){eval("this.setting.list"+n+'="'+value+'"');
};
this.getCampaign=function(){return this.setting.campaign;
};
this.setCampaign=function(c){this.setting.campaign=c;
};
this.getEvents=function(){return this.setting.events;
};
this.setEvents=function(e){this.setting.events=e;
};
this.getProducts=function(){return this.setting.products;
};
this.setProducts=function(p){this.setting.products=p;
};
this.isLink=function(){return this.setting.lnk;
};
this.setLink=function(lnk){this.setting.lnk=lnk;
};
this.getLinkType=function(){return this.setting.linkType;
};
this.setLinkType=function(linkType){this.setting.linkType=linkType;
};
this.getLinkName=function(){return this.setting.linkName;
};
this.setLinkName=function(linkName){this.setting.linkName=linkName;
};
}
if(typeof KIDS=="undefined"||!KIDS){var KIDS={};
}KIDS.namespace("reporting");
KIDS.reporting.config;
KIDS.reporting.qs;
Configuration.prototype.initialize=function(){this.init();
this.setting.name="vianickjr";
this.setting.dynamicAccountSelection="true";
this.setting.dynamicAccountList="devvianickjr=mtvi.com,localhost,9090";
this.setting.linkInternalFilters="javascript:,nickjr.com";
this.setting.trackExternalLinks=true;
this.setting.trackDownloadLinks=true;
this.setting.trackInlineStats=true;
if(!this.isLink()){if(KIDS.get("reportingKey").length>0){this.setting.pageName=KIDS.get("reportingKey");
}else{if(KIDS.get("categoryPath").length>0){this.setting.pageName=KIDS.get("categoryPath");
}}this.setting.pageName=this.setting.pageName.replace(/\/2009-Redesign/,"");
if(this.setting.pageName.indexOf(".")<0){if(this.setting.pageName.lastIndexOf("/")!=this.setting.pageName.length-1){this.setting.pageName+="/";
}this.setting.hier2=this.setting.pageName.substr(1)+"index";
}else{this.setting.hier2=this.setting.pageName.substr(1,this.setting.pageName.lastIndexOf(".")-1);
}this.setting.channel=this.setting.hier2.substr(0,this.setting.hier2.indexOf("/"));
if(KIDS.get("adfree")=="true"){this.setting.channel="AdFreePages";
}if(this.setting.pageName.indexOf("/doras-tenth/")>-1||this.setting.pageName.indexOf("/beyond-the-backpack/")>-1){this.setting.prop2="Doras Tenth";
}if(KIDS.get("uri")=="/app/standalonePrintablePageController/"||KIDS.get("uri")=="/app/standaloneGamePageController/"){this.setting.channel="BeyondTheBackpack.com";
this.setting.pageName="/BeyondTheBackpack.com/"+KIDS.get("type")+"/"+KIDS.get("urlAlias")+".html";
this.setting.hier2=this.setting.pageName.substr(1,this.setting.pageName.lastIndexOf(".")-1);
this.setting.prop12="BeyondTheBackpack";
this.setting.eVar8="BeyondTheBackpack";
}this.setting.prop3=location.search;
if(KIDS.get("type")=="gameItem"){this.setting.prop4=KIDS.get("urlAlias");
if(this.setting.events.length>0){this.setting.events+=",";
}this.setting.events+="event14";
this.setting.prop29=KIDS.get("cmsId");
}if(KIDS.get("type")=="printableItem"){this.setting.prop24=KIDS.get("cmsId");
}this.setting.prop10=KIDS.get("showId");
var a=KIDS.reporting.qs.xid?KIDS.reporting.qs.xid:"";
if(a.length>0){var b=new Date();
b.setDate(b.getDate()+30);
document.cookie="NICKJR.xid="+a+";expires="+b.toGMTString();
}a=KIDS.utils.getCookie("NICKJR.xid");
a=(a==null)?"":a;
this.setting.prop6=a;
this.setting.eVar7=a;
this.setting.campaign=a;
if(a.length>0){if(this.setting.events.length>0){this.setting.events+=",";
}this.setting.events+="event5";
}this.setting.prop42=this.setting.campaign;
this.setting.eVar16=this.setting.pageName;
this.setting.eVar13=KIDS.reporting.qs.navid;
btg.config.Omniture.percentPageViewedVarMap={previousPage:"prop54",percentage:"prop55"};
if(KIDS.get("preloaderSetting")!=""){this.setting.eVar40=KIDS.get("preloaderSetting");
}else{if(KIDS.get("uri")=="/app/kidsGamePageController/"){this.setting.eVar40="No Ad";
}}}};
KIDS.reporting.init=function(){KIDS.reporting.qs=btg.String.queryStringToObject(location.href);
KIDS.reporting.config=new Configuration();
KIDS.reporting.config.initialize();
if(location.pathname.indexOf("/nickjr20122015/kids/")>-1||location.pathname.indexOf("/nickjr20122015/kids-games/")>-1||location.pathname.indexOf("/nickjr20122015/kids-videos/")>-1||location.pathname.indexOf("/nickjr20122015/kids-create/")>-1){KIDS.reporting.config.setProp(11,"kids");
}else{KIDS.reporting.config.setProp(11,"grownups");
}btg.Controller.init();
KIDS.reporting.config.setProp(9,KIDS.reporting.qs.partner);
KIDS.reporting.config.setEVar(2,KIDS.reporting.qs.searchterm?com.mtvi.config.qs.searchterm:"");
KIDS.reporting.config.setEVar(3,KIDS.reporting.qs.searchtype?com.mtvi.config.qs.searchtype:"");
KIDS.reporting.config.setProp(17,KIDS.reporting.config.getEVar(2));
};
KIDS.reporting.firePageLoad=function(){if(location.href.indexOf("ad-entry")<0){KIDS.reporting.omnifunctions.sendReportingCall();
}};

if(location.pathname.indexOf("/nickjr20122015/kids/")==0||location.pathname.indexOf("/nickjr20122015/kids-games/")==0||location.pathname.indexOf("/nickjr20122015/kids-videos/")==0||location.pathname.indexOf("/nickjr20122015/kids-create/")==0){btg.config.DoubleClick.dartSite="nickjr.playtime.nol";
}else{btg.config.DoubleClick.dartSite="nickjr.nol";
}btg.config.DoubleClick.positionThreshold=3;

KIDS.namespace("reporting.omnifunctions");
KIDS.reporting.omnifunctions.nrtrackingcode="";
KIDS.reporting.omnifunctions.NRcall="";
KIDS.reporting.omnifunctions.sendAnalyticsEvent=function(c){try{var a=new Configuration();
a.init();
if(btg.String.isDefined(c)){a.setting.name+=","+c;
}KIDS.reporting.omnifunctions.sendReportingCall(a);
}catch(b){KIDS.utils.doLog(b.toString());
}};
KIDS.reporting.omnifunctions.sendLinkEvent=function(d,b){try{var a=KIDS.reporting.config.setting.name;
if(btg.String.isDefined(d)){btg.config.Omniture.account+=","+d;
btg.Controller.init();
}btg.Controller.sendLinkEvent({linkName:b,linkType:"o"});
if(btg.String.isDefined(d)){btg.config.Omniture.account=a;
btg.Controller.init();
}}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.sendReportingCall=function(b){try{if(b==null){b=KIDS.reporting.config;
}if(b.getPageName().indexOf("ads.comscore")<0){var a=KIDS.reporting.config.setting.name;
if(btg.String.isDefined(b.setting.name)){btg.config.Omniture.account=b.setting.name;
}btg.Controller.init();
btg.Controller.sendPageCall(b.setting);
if(btg.String.isDefined(b.setting.name)){btg.config.Omniture.account=a;
btg.Controller.init();
}}}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.oldReportingCall=function(b){try{var a=new Configuration(KIDS.reporting.config);
a.init();
var d=b.setOverrides;
KIDS.reporting.omnifunctions.omniSetOverrides(d,"overwrite",a);
KIDS.reporting.omnifunctions.sendReportingCall(a);
}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.omniSetOverrides=function(f,g,a){try{for(i in f){var b=i.replace(/s_/,"");
b=(b=="account")?"name":b;
a.setting[b]=f[i];
if(b=="name"){if(g){if(g=="append"){var c=new RegExp("^"+ro[b]+"$|^"+ro[b]+",|,"+ro[b]+"$|,"+ro[b]+",");
if(!c.test(KIDS.reporting.config.getName())){a.setName(KIDS.reporting.config.getName()+","+a.getName());
}}}}}}catch(d){KIDS.utils.doLog(d.toString());
}};
KIDS.reporting.omnifunctions.sendLinkCall=function(d,a){try{var b=unescape(d);
if(a){if(a.setOverrides.name){KIDS.reporting.omnifunctions.sendLinkEvent(a.setOverrides.name,b);
}else{if(a.setOverrides.s_account){KIDS.reporting.omnifunctions.sendLinkEvent(a.setOverrides.s_account,b);
}}}else{KIDS.reporting.omnifunctions.sendLinkEvent(null,b);
}}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.sendReportingCallTN2=function(b){try{var a=new Configuration(KIDS.reporting.config);
a.init();
var d=b.setOverrides;
d.name="vianickvision";
KIDS.reporting.omnifunctions.omniSetOverrides(d,"append",a);
KIDS.reporting.omnifunctions.sendReportingCall(a);
}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.sendInitCall=function(d,c,a){try{elementString=d+"-"+c+"-"+a;
linkName="/init_click_tracking/"+elementString;
KIDS.reporting.omnifunctions.sendLinkEvent(null,linkName);
}catch(b){KIDS.utils.doLog(b.toString());
}};
KIDS.reporting.omnifunctions.TrackLinkNickJr=function(d,c,a){try{KIDS.reporting.omnifunctions.sendInitCall(d,c,a);
}catch(b){KIDS.utils.doLog(b.toString());
}};
KIDS.reporting.omnifunctions.comscoreReport=function(a){try{var c='<iframe id="'+a+'" src="/ads.comscore" style="overflow:hidden;margin:0px;padding:0px;display:none;" scrolling="no" width="1" height="1" frameborder="0"></iframe>';
if($("#"+a).length){$("#"+a).replaceWith(c);
}else{$(c).appendTo("body");
}}catch(b){}};
KIDS.reporting.omnifunctions.pageNameAppend=function(c){try{var b=new Configuration();
b.initialize();
var a=KIDS.reporting.config.getPageName();
b.setPageName(a+"-"+c);
if(c!="games"){b.setProp("4",c);
}KIDS.reporting.omnifunctions.sendReportingCall(b);
}catch(d){KIDS.utils.doLog(d.toString());
}};
KIDS.reporting.omnifunctions.pageNameReset=function(b){try{var a=new Configuration();
a.initialize();
a.setPageName(b);
KIDS.reporting.omnifunctions.sendReportingCall(a);
}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.trackKidsGamePlay=function(f){try{var b=new Configuration();
b.init();
var a=fetchGamePlaySite(document.URL);
var c="viakidsgameplay";
b.setName(c);
b.setDynamicAccountSelection("false");
b.setChannel(a);
b.setHier1(a+"/"+f);
b.setHier2("");
b.setProp(1,b.getHier1());
b.setProp(2,f);
b.setProp(3,a);
KIDS.reporting.omnifunctions.sendReportingCall(b);
}catch(d){KIDS.utils.doLog(d.toString());
}};
KIDS.reporting.omnifunctions.fetchGamePlaySite=function(c){try{var d=new RegExp("(nick)(?:-(?:jd|d|jq|q).mtvi)?.com","gi");
var a=d.exec(c);
if(a){d=new RegExp("/(turbonick|nicktropolis)/","gi");
var b=d.exec(c);
if(b){return(b[1]);
}return(a[1]);
}else{d=new RegExp("(nickjr)(?:-[dq].mtvi)?.com","gi");
a=d.exec(c);
if(a){if(c.indexOf("/playtime/")>0){return("playtime");
}return(a[1]);
}else{d=new RegExp("(noggin)(?:-[dq].mtvi)?.com","gi");
a=d.exec(c);
if(a){return(a[1]);
}else{d=new RegExp("(shockwave|addictinggames|the-n).*.com","gi");
a=d.exec(c);
if(a){return(a[1]);
}else{d=new RegExp("localhost:9090","gi");
a=d.exec(c);
if(a){return("nickjr-localhost");
}else{return(null);
}}}}}}catch(f){KIDS.utils.doLog(f.toString());
}};
KIDS.reporting.omnifunctions.flashReport=function(a){try{KIDS.reporting.omnifunctions.pageNameAppend(a);
}catch(b){KIDS.utils.doLog(b.toString());
}};
KIDS.reporting.omnifunctions.printTracker=function(b,k,h,g){try{var f=new Configuration(KIDS.reporting.config);
f.init();
var a="nickjr";
f.setName("viakfprint");
f.setPageName(a+"-"+k+"-"+h+"-"+b);
f.setChannel(a);
f.setHier1(a+"/"+k+"/"+h+"/"+b);
f.setHier2(f.getHier1());
f.setProp(1,g);
f.setProp(2,a);
f.setProp(3,k);
f.setProp(4,h);
f.setProp(5,b);
KIDS.reporting.omnifunctions.sendReportingCall(f);
var j="http://ad.doubleclick.net/ad/nickjr.nol/hp_printables;adid=227986931;sz=1x1;ord=2654564545?";
var c=document.createElement("img");
c.setAttribute("src",j);
btg.Controller.init();
btg.Controller.sendLinkEvent({pageName:"",linkName:b,linkType:"o",events:"event9",eVar24:b});
}catch(d){KIDS.utils.doLog(d.toString());
}};
KIDS.reporting.omnifunctions.printReporting=function(a,b,k,h,g){try{var f=new Configuration(KIDS.reporting.config);
f.init();
f.setName("viakfprint");
f.setPageName(a+"-"+k+"-"+h+"-"+b);
f.setChannel(a);
f.setHier1(a+"/"+k+"/"+h+"/"+b);
f.setHier2(f.getHier1());
f.setProp(1,g);
f.setProp(2,a);
f.setProp(3,k);
f.setProp(4,h);
f.setProp(5,b);
KIDS.reporting.omnifunctions.sendReportingCall(f);
var j="http://ad.doubleclick.net/ad/nickjr.nol/hp_printables;adid=227986931;sz=1x1;ord=2654564545?";
var c=document.createElement("img");
c.setAttribute("src",j);
btg.Controller.init();
btg.Controller.sendLinkEvent({pageName:"",linkName:b,linkType:"o",events:"event9",eVar24:b});
}catch(d){KIDS.utils.doLog(d.toString());
}};
KIDS.reporting.omnifunctions.trackFlashClicks=function(b,e,d){var c=e.substr(0,18);
var a=String(b)+"__"+String(c)+"__"+String(d);
KIDS.reporting.omnifunctions.pageNameAppend(a);
};
KIDS.reporting.omnifunctions.dorasWorldGame=function(f,d,a){try{var b=new Configuration();
b.init();
b.setName("vianickjr");
b.setDynamicAccountSelection("true");
b.setDynamicAccountList("devvianickjr=nickjr-d.mtvi.com,nickjr-q.mtvi.com");
b.setLinkInternalFilters("javascript:,nickjr.com");
b.setTrackExternalLinks(true);
b.setTrackDownloadLinks(true);
b.setTrackInlineStats(true);
b.setProp(4,"DorasWorld_"+d);
b.setProp(5,"DorasWorld_"+d);
b.setProp(7,d);
if(NICKJR){if(NICKJR.profile.flashapi.isLoggedIn()){b.setProp(8,"UserLoggedIn");
}else{b.setProp(8,"UserNotLoggedIn");
}}b.setPageName(location.pathname+"/"+f+"/"+d);
b.setHier2("kids/kids-games/doras-great-big-world-game.html");
KIDS.reporting.omnifunctions.sendReportingCall(b);
}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.dorasWorldLocation=function(d,a){try{var b=new Configuration();
b.init();
b.setName("vianickjr");
b.setDynamicAccountSelection("true");
b.setDynamicAccountList("devvianickjr=nickjr-d.mtvi.com,nickjr-q.mtvi.com");
b.setLinkInternalFilters("javascript:,nickjr.com");
b.setTrackExternalLinks(true);
b.setTrackDownloadLinks(true);
b.setTrackInlineStats(true);
b.setPageName(location.pathname+"/"+d);
b.setHier2(location.pathname+"/"+d);
if(NICKJR){if(NICKJR.profile.flashapi.isLoggedIn()){b.setProp(8,"UserLoggedIn");
}else{b.setProp(8,"UserNotLoggedIn");
}}KIDS.reporting.omnifunctions.sendReportingCall(b);
}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.DoraWeDidIt=function(a){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,"Explore with Dora - We Did It - "+a);
}catch(b){KIDS.utils.doLog(b.toString());
}};
KIDS.reporting.omnifunctions.tabReporting=function(b,c){try{var a=new Configuration();
a.initialize();
a.setName("vianickjr");
a.setDynamicAccountSelection("true");
a.setDynamicAccountList("devvianickjr=nickjr-d.mtvi.com,nickjr-q.mtvi.com");
a.setLinkInternalFilters("javascript:,nickjr.com");
a.setTrackExternalLinks(true);
a.setTrackDownloadLinks(true);
a.setTrackInlineStats(true);
a.setPageName(a.getPageName()+b+" - "+c);
a.setHier2(a.getPageName());
KIDS.reporting.omnifunctions.sendReportingCall(a);
}catch(d){KIDS.utils.doLog(d.toString());
}};
KIDS.reporting.omnifunctions.galleryPhotoClick=function(a){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,a+" - Photo Gallery Click");
}catch(b){KIDS.utils.doLog(b.toString());
}};
KIDS.reporting.omnifunctions.DoraBackpackSubmitEvent=function(){try{if(location.pathname.indexOf("spanish")>-1){KIDS.reporting.omnifunctions.sendLinkEvent(null,"Dora's Beyond the Backpack - Spanish Checklist/Quiz Submit");
}else{KIDS.reporting.omnifunctions.sendLinkEvent(null,"Dora's Beyond the Backpack - English Checklist/Quiz Submit");
}}catch(a){KIDS.utils.doLog(a.toString());
}};
KIDS.reporting.omnifunctions.boostPromoEvent=function(){try{if(location.pathname.indexOf("spanish")>-1){KIDS.reporting.omnifunctions.sendLinkEvent(null,"Dora's Beyond the Backpack - Spanish Results - Boost Promo");
}else{KIDS.reporting.omnifunctions.sendLinkEvent(null,"Dora's Beyond the Backpack - English Results - Boost Promo");
}}catch(a){KIDS.utils.doLog(a.toString());
}};
KIDS.reporting.omnifunctions.sendLogin=function(){try{var a=new Configuration();
a.init();
a.setName("vianickjr");
a.setDynamicAccountSelection("true");
a.setDynamicAccountList("devvianickjr=nickjr-d.mtvi.com,nickjr-q.mtvi.com");
a.setLinkInternalFilters("javascript:,nickjr.com");
a.setTrackExternalLinks(true);
a.setTrackDownloadLinks(true);
a.setTrackInlineStats(true);
a.setPageName("/LoginComplete");
a.setHier2("LoginComplete");
a.setEvents("event4");
KIDS.reporting.omnifunctions.sendReportingCall(a);
}catch(b){}};
KIDS.reporting.omnifunctions.UGVUploadEvent=function(){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,KIDS.reporting.config.getPageName()+" - Upload Your Video");
}catch(a){KIDS.utils.doLog(a.toString());
}};
KIDS.reporting.omnifunctions.UGVVideoThumbnailEvent=function(){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,KIDS.reporting.config.getPageName()+" - Video Thumbnail");
}catch(a){KIDS.utils.doLog(a.toString());
}};
KIDS.reporting.omnifunctions.UGVViewAllEvent=function(){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,KIDS.reporting.config.getPageName()+" - View All");
}catch(a){KIDS.utils.doLog(a.toString());
}};
KIDS.reporting.omnifunctions.UGVMostEvent=function(b){try{KIDS.reporting.omnifunctions.pageNameAppend(b);
}catch(a){}};
KIDS.reporting.omnifunctions.doraInvitationSend=function(a){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,KIDS.reporting.config.getPageName()+" - Send Invitation - "+a+" invited");
}catch(b){}};
KIDS.reporting.omnifunctions.doraInvitationShare=function(a){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,KIDS.reporting.config.getPageName()+" - Share on "+a);
}catch(b){}};
KIDS.reporting.omnifunctions.doraInvitationNewsLetter=function(){try{KIDS.reporting.omnifunctions.sendLinkEvent(null,KIDS.reporting.config.getPageName()+" - Newsletter Signup");
}catch(a){}};
KIDS.reporting.omnifunctions.doraInvitationPlayAgain=function(){try{KIDS.reporting.omnifunctions.pageNameAppend("Play Again");
}catch(a){}};
KIDS.reporting.omnifunctions.umiCityLocation=function(b){try{var a=new Configuration(KIDS.reporting.config);
a.init();
a.setName("vianickjr");
a.setPageName(a.getPageName()+"/"+b);
a.setHier2(a.getPageName());
KIDS.reporting.omnifunctions.sendReportingCall(a);
}catch(c){KIDS.utils.doLog(c.toString());
}};
KIDS.reporting.omnifunctions.BTBPrintTracker=function(a,c){try{KIDS.reporting.omnifunctions.printTracker(a,"BeyondTheBackpackPrintable",c,"1");
}catch(b){KIDS.utils.doLog(b.toString());
}};
_nrtrackingcode=KIDS.reporting.omnifunctions.nrtrackingcode;
NRcall=KIDS.reporting.omnifunctions.NRcall;
sendAnalyticsEvent=KIDS.reporting.omnifunctions.sendAnalyticsEvent;
sendLinkEvent=KIDS.reporting.omnifunctions.sendLinkEvent;
sendReportingCall=KIDS.reporting.omnifunctions.oldReportingCall;
omniSetOverrides=KIDS.reporting.omnifunctions.omniSetOverrides;
sendLinkCall=KIDS.reporting.omnifunctions.sendLinkCall;
sendReportingCallTN2=KIDS.reporting.omnifunctions.sendReportingCallTN2;
sendInitCall=KIDS.reporting.omnifunctions.sendInitCall;
TrackLinkNickJr=KIDS.reporting.omnifunctions.TrackLinkNickJr;
pageNameAppend=KIDS.reporting.omnifunctions.pageNameAppend;
pageNameReset=KIDS.reporting.omnifunctions.pageNameReset;
trackKidsGamePlay=KIDS.reporting.omnifunctions.trackKidsGamePlay;
fetchGamePlaySite=KIDS.reporting.omnifunctions.fetchGamePlaySite;
flashReport=KIDS.reporting.omnifunctions.flashReport;
printTracker=KIDS.reporting.omnifunctions.printTracker;
printReporting=KIDS.reporting.omnifunctions.printReporting;
dorasWorldGame=KIDS.reporting.omnifunctions.dorasWorldGame;
dorasWorldLocation=KIDS.reporting.omnifunctions.dorasWorldLocation;

if(typeof KIDS=="undefined"||!KIDS){var KIDS={};
}KIDS.namespace("ads.refresh");
KIDS.ads.refresh.placeAd=function(k){try{if(KIDS.get("adfree")!="true"){var g=k.substring(k.indexOf("-")+1,k.indexOf("D"));
for(var b=0;
b<KIDS.ads.adArray.length;
b++){var l=KIDS.ads.adArray[b];
if(g==l.getSize()){if(g.indexOf("-")>0){g=g.substring(0,g.indexOf("-"));
}var m=l.getActualSize();
if(typeof btg.DoubleClick.createAd=="function"){if(m!=""){g=m;
}}var j=l.getContentType();
var h=l.getKeyValues();
if(h.indexOf("pos=")>-1){h=h.substring(0,h.indexOf("pos="))+h.substring(h.indexOf("pos=")+8);
}var a=KIDS.ads.pageLevelAdConfig.keyValues+h;
var f="";
if(l.isRefreshable()){f=parseInt(l.getRefreshRate());
if(isNaN(f)||f<0.5){f=0.5;
}f*=60000;
}var c=KIDS.ads.pageLevelAdConfig.zone;
if(j=="adi"&&!l.isRefreshable()){mtvn.btg.Controller.placeAd({size:g,keyValues:a,sections:c,contentType:"adi"});
}else{if(j=="adj"){if(!l.isRefreshable()){mtvn.btg.Controller.placeAd({size:g,keyValues:a,sections:c});
}else{mtvn.btg.Controller.placeAd({size:g,realSize:m,keyValues:a,sections:c,isReloadable:l.isRefreshable(),reloadInterval:f});
}}}}}}}catch(d){KIDS.utils.doLog("KIDS.ads.refresh.placeAd failed:"+d);
}};